[package]
name = "regex_derivatives"
version = "0.1.0"
authors = ["Elf M. Sternberg <elf.sternberg@gmail.com>"]
description = "An implementation of Matt Might's Parsing With Derivatives."
# edition = "2018"

[dependencies]
rand = "0.5.5"

[dev-dependencies]
